version: '3.8'
services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    volumes:
      - ~/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - apc-api-network
    ports:
      - 27021:27017
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']
  mongo2:
    container_name: mongo2
    image: mongo:latest
    volumes:
      - ~/mongors/data2:/data/db
    networks:
      - apc-api-network
    ports:
      - 27022:27017
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']
  mongo3:
    container_name: mongo3
    image: mongo:latest
    volumes:
      - ~/mongors/data3:/data/db
    networks:
      - apc-api-network
    ports:
      - 27023:27017
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'dbrs']

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - apc-api-network

networks:
  apc-api-network:
    driver: bridge
